env: standard
runtime: nodejs16
service: default
handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  DATABASE_URL: "postgres://hzotqivrzlsxsb:220f11ab23b748cf1a485b20616a627ab4216ba0e0726657e67992d6e661153d@ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/d727e2adk145p1"
